POST http://localhost:3333/classes
Content-Type: application/json

{
    "name": "Cherry",
    "avatar": "https://avatars3.githubusercontent.com/u/43519162?v=4",
    "whatsapp": "19974154036",
    "bio": "I enjoy javascript, typescript and java",
    "subject": "Historia",
    "cost": 80,
    "schedule": [
      { "week_day": 1, "from": "8:00", "to": "12:00" },
      { "week_day": 3, "from": "10:00", "to": "18:00" },
      { "week_day": 4, "from": "8:00", "to": "12:00" }
    ]
}
